on:

  workflow_dispatch:

 

name: sp-dev

jobs:

  deploy:

    environment: AZURE_CONNECTION_DEV

    runs-on: ubuntu-latest

    steps:

      # Checkout code

    - uses: actions/checkout@main



      # Log into Azure

    - uses: azure/login@v1

      with:

        creds: ${{ secrets.AZURE_CONNECTION_ID }}



    - name: deploy_dev_storage

      uses: azure/arm-deploy@v1

      with:

        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        resourceGroupName: ${{ secrets.LAB_AZURE_RG }}

        template: ./code/storage.json
